import type { editor } from "monaco-editor";

export type ThemeId =
  | "vs-dark"
  | "vs-light"
  | "hc-black"
  | "hc-light"
  | "monokai"
  | "dracula"
  | "github-dark"
  | "github-light"
  | "solarized-dark"
  | "solarized-light"
  | "abyss"
  | "tomorrow-night-blue"
  | "one-dark"
  | "quiet-light";

export interface ThemeConfig {
  label: string;
  mode: "dark" | "light";
  monacoTheme: string;
  cssVars?: Record<string, string>;
  customTheme?: editor.IStandaloneThemeData;
}

export const THEME_LIST: { id: ThemeId; label: string; mode: "dark" | "light" }[] = [
  { id: "vs-dark", label: "Dark+", mode: "dark" },
  { id: "monokai", label: "Monokai", mode: "dark" },
  { id: "dracula", label: "Dracula", mode: "dark" },
  { id: "one-dark", label: "One Dark", mode: "dark" },
  { id: "github-dark", label: "GitHub Dark", mode: "dark" },
  { id: "solarized-dark", label: "Solarized Dark", mode: "dark" },
  { id: "abyss", label: "Abyss", mode: "dark" },
  { id: "tomorrow-night-blue", label: "Tomorrow Night Blue", mode: "dark" },
  { id: "hc-black", label: "High Contrast", mode: "dark" },
  { id: "vs-light", label: "Light+", mode: "light" },
  { id: "quiet-light", label: "Quiet Light", mode: "light" },
  { id: "github-light", label: "GitHub Light", mode: "light" },
  { id: "solarized-light", label: "Solarized Light", mode: "light" },
  { id: "hc-light", label: "High Contrast Light", mode: "light" },
];

export const THEMES: Record<ThemeId, ThemeConfig> = {
  "vs-dark": {
    label: "Dark+",
    mode: "dark",
    monacoTheme: "vs-dark",
  },
  "vs-light": {
    label: "Light+",
    mode: "light",
    monacoTheme: "vs",
  },
  "hc-black": {
    label: "High Contrast",
    mode: "dark",
    monacoTheme: "hc-black",
    cssVars: {
      "--primary": "180 100% 50%",
      "--ring": "180 100% 50%",
      "--sidebar-primary": "180 100% 50%",
      "--sidebar-ring": "180 100% 50%",
      "--accent": "180 60% 12%",
      "--accent-foreground": "180 100% 75%",
      "--border": "0 0% 40%",
      "--sidebar-border": "0 0% 40%",
    },
  },
  "hc-light": {
    label: "High Contrast Light",
    mode: "light",
    monacoTheme: "hc-light",
    cssVars: {
      "--primary": "240 100% 40%",
      "--ring": "240 100% 40%",
      "--sidebar-primary": "240 100% 40%",
      "--sidebar-ring": "240 100% 40%",
      "--accent": "240 30% 88%",
      "--accent-foreground": "240 60% 20%",
      "--border": "0 0% 20%",
    },
    customTheme: {
      base: "vs",
      inherit: true,
      rules: [
        { token: "", foreground: "292929" },
        { token: "comment", foreground: "008000" },
        { token: "keyword", foreground: "0000FF", fontStyle: "bold" },
        { token: "string", foreground: "A31515" },
        { token: "number", foreground: "098658" },
      ],
      colors: {
        "editor.background": "#FFFFFF",
        "editor.foreground": "#292929",
        "editorCursor.foreground": "#000000",
        "editor.selectionBackground": "#ADD6FF",
        "editor.lineHighlightBackground": "#F0F0F0",
        "editorLineNumber.foreground": "#292929",
      },
    },
  },
  monokai: {
    label: "Monokai",
    mode: "dark",
    monacoTheme: "monokai",
    cssVars: {
      "--background": "70 8% 11%",
      "--foreground": "60 10% 96%",
      "--card": "70 8% 13%",
      "--card-border": "70 8% 18%",
      "--sidebar": "70 8% 15%",
      "--sidebar-border": "70 8% 20%",
      "--border": "70 8% 20%",
      "--primary": "340 94% 58%",
      "--primary-foreground": "0 0% 98%",
      "--ring": "340 94% 58%",
      "--sidebar-primary": "340 94% 58%",
      "--sidebar-ring": "340 94% 58%",
      "--accent": "340 30% 22%",
      "--accent-foreground": "340 80% 82%",
      "--muted": "70 8% 18%",
      "--muted-foreground": "70 5% 60%",
    },
    customTheme: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", foreground: "F8F8F2", background: "272822" },
        { token: "comment", foreground: "75715E", fontStyle: "italic" },
        { token: "keyword", foreground: "F92672" },
        { token: "string", foreground: "E6DB74" },
        { token: "number", foreground: "AE81FF" },
        { token: "type", foreground: "66D9EF", fontStyle: "italic" },
        { token: "function", foreground: "A6E22E" },
        { token: "variable", foreground: "F8F8F2" },
        { token: "constant", foreground: "AE81FF" },
        { token: "tag", foreground: "F92672" },
        { token: "attribute.name", foreground: "A6E22E" },
        { token: "attribute.value", foreground: "E6DB74" },
        { token: "delimiter", foreground: "F8F8F2" },
        { token: "operator", foreground: "F92672" },
      ],
      colors: {
        "editor.background": "#272822",
        "editor.foreground": "#F8F8F2",
        "editorCursor.foreground": "#F8F8F0",
        "editor.selectionBackground": "#49483E",
        "editor.lineHighlightBackground": "#3E3D32",
        "editorLineNumber.foreground": "#90908A",
        "editorIndentGuide.background": "#464741",
      },
    },
  },
  dracula: {
    label: "Dracula",
    mode: "dark",
    monacoTheme: "dracula",
    cssVars: {
      "--background": "231 15% 13%",
      "--foreground": "60 30% 96%",
      "--card": "232 14% 16%",
      "--card-border": "232 14% 20%",
      "--sidebar": "232 14% 17%",
      "--sidebar-border": "232 14% 22%",
      "--border": "232 14% 22%",
      "--primary": "265 89% 78%",
      "--primary-foreground": "0 0% 10%",
      "--ring": "265 89% 78%",
      "--sidebar-primary": "265 89% 78%",
      "--sidebar-ring": "265 89% 78%",
      "--accent": "265 25% 24%",
      "--accent-foreground": "265 80% 88%",
      "--muted": "232 14% 22%",
      "--muted-foreground": "232 10% 60%",
    },
    customTheme: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", foreground: "F8F8F2", background: "282A36" },
        { token: "comment", foreground: "6272A4", fontStyle: "italic" },
        { token: "keyword", foreground: "FF79C6" },
        { token: "string", foreground: "F1FA8C" },
        { token: "number", foreground: "BD93F9" },
        { token: "type", foreground: "8BE9FD", fontStyle: "italic" },
        { token: "function", foreground: "50FA7B" },
        { token: "variable", foreground: "F8F8F2" },
        { token: "constant", foreground: "BD93F9" },
        { token: "tag", foreground: "FF79C6" },
        { token: "attribute.name", foreground: "50FA7B" },
        { token: "attribute.value", foreground: "F1FA8C" },
        { token: "delimiter", foreground: "F8F8F2" },
        { token: "operator", foreground: "FF79C6" },
      ],
      colors: {
        "editor.background": "#282A36",
        "editor.foreground": "#F8F8F2",
        "editorCursor.foreground": "#F8F8F0",
        "editor.selectionBackground": "#44475A",
        "editor.lineHighlightBackground": "#44475A75",
        "editorLineNumber.foreground": "#6272A4",
        "editorIndentGuide.background": "#424450",
      },
    },
  },
  "one-dark": {
    label: "One Dark",
    mode: "dark",
    monacoTheme: "one-dark",
    cssVars: {
      "--background": "220 13% 11%",
      "--foreground": "220 14% 72%",
      "--card": "220 13% 13%",
      "--card-border": "220 13% 18%",
      "--sidebar": "220 13% 14%",
      "--sidebar-border": "220 13% 19%",
      "--border": "220 13% 19%",
      "--primary": "207 82% 66%",
      "--primary-foreground": "0 0% 10%",
      "--ring": "207 82% 66%",
      "--sidebar-primary": "207 82% 66%",
      "--sidebar-ring": "207 82% 66%",
      "--accent": "207 30% 20%",
      "--accent-foreground": "207 70% 80%",
      "--muted": "220 13% 18%",
      "--muted-foreground": "220 10% 55%",
    },
    customTheme: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", foreground: "ABB2BF", background: "282C34" },
        { token: "comment", foreground: "5C6370", fontStyle: "italic" },
        { token: "keyword", foreground: "C678DD" },
        { token: "string", foreground: "98C379" },
        { token: "number", foreground: "D19A66" },
        { token: "type", foreground: "E5C07B" },
        { token: "function", foreground: "61AFEF" },
        { token: "variable", foreground: "E06C75" },
        { token: "constant", foreground: "D19A66" },
        { token: "tag", foreground: "E06C75" },
        { token: "attribute.name", foreground: "D19A66" },
        { token: "attribute.value", foreground: "98C379" },
        { token: "delimiter", foreground: "ABB2BF" },
        { token: "operator", foreground: "56B6C2" },
      ],
      colors: {
        "editor.background": "#282C34",
        "editor.foreground": "#ABB2BF",
        "editorCursor.foreground": "#528BFF",
        "editor.selectionBackground": "#3E4451",
        "editor.lineHighlightBackground": "#2C313C",
        "editorLineNumber.foreground": "#495162",
        "editorIndentGuide.background": "#3B4048",
      },
    },
  },
  "github-dark": {
    label: "GitHub Dark",
    mode: "dark",
    monacoTheme: "github-dark",
    cssVars: {
      "--background": "215 28% 7%",
      "--foreground": "213 26% 84%",
      "--card": "215 28% 9%",
      "--card-border": "215 28% 13%",
      "--sidebar": "215 28% 10%",
      "--sidebar-border": "215 28% 14%",
      "--border": "215 28% 14%",
      "--primary": "212 100% 67%",
      "--primary-foreground": "0 0% 5%",
      "--ring": "212 100% 67%",
      "--sidebar-primary": "212 100% 67%",
      "--sidebar-ring": "212 100% 67%",
      "--accent": "212 40% 16%",
      "--accent-foreground": "212 80% 80%",
      "--muted": "215 28% 14%",
      "--muted-foreground": "213 15% 55%",
    },
    customTheme: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", foreground: "C9D1D9", background: "0D1117" },
        { token: "comment", foreground: "8B949E", fontStyle: "italic" },
        { token: "keyword", foreground: "FF7B72" },
        { token: "string", foreground: "A5D6FF" },
        { token: "number", foreground: "79C0FF" },
        { token: "type", foreground: "FFA657" },
        { token: "function", foreground: "D2A8FF" },
        { token: "variable", foreground: "FFA657" },
        { token: "constant", foreground: "79C0FF" },
        { token: "tag", foreground: "7EE787" },
        { token: "attribute.name", foreground: "79C0FF" },
        { token: "attribute.value", foreground: "A5D6FF" },
        { token: "delimiter", foreground: "C9D1D9" },
        { token: "operator", foreground: "FF7B72" },
      ],
      colors: {
        "editor.background": "#0D1117",
        "editor.foreground": "#C9D1D9",
        "editorCursor.foreground": "#58A6FF",
        "editor.selectionBackground": "#264F78",
        "editor.lineHighlightBackground": "#161B22",
        "editorLineNumber.foreground": "#484F58",
        "editorIndentGuide.background": "#21262D",
      },
    },
  },
  "github-light": {
    label: "GitHub Light",
    mode: "light",
    monacoTheme: "github-light",
    cssVars: {
      "--primary": "212 97% 43%",
      "--primary-foreground": "0 0% 100%",
      "--ring": "212 97% 43%",
      "--sidebar-primary": "212 97% 43%",
      "--sidebar-ring": "212 97% 43%",
      "--accent": "212 55% 91%",
      "--accent-foreground": "212 60% 22%",
    },
    customTheme: {
      base: "vs",
      inherit: true,
      rules: [
        { token: "", foreground: "24292F", background: "FFFFFF" },
        { token: "comment", foreground: "6E7781", fontStyle: "italic" },
        { token: "keyword", foreground: "CF222E" },
        { token: "string", foreground: "0A3069" },
        { token: "number", foreground: "0550AE" },
        { token: "type", foreground: "953800" },
        { token: "function", foreground: "8250DF" },
        { token: "variable", foreground: "953800" },
        { token: "constant", foreground: "0550AE" },
        { token: "tag", foreground: "116329" },
        { token: "attribute.name", foreground: "0550AE" },
        { token: "attribute.value", foreground: "0A3069" },
        { token: "delimiter", foreground: "24292F" },
        { token: "operator", foreground: "CF222E" },
      ],
      colors: {
        "editor.background": "#FFFFFF",
        "editor.foreground": "#24292F",
        "editorCursor.foreground": "#044289",
        "editor.selectionBackground": "#BBDFFF",
        "editor.lineHighlightBackground": "#F6F8FA",
        "editorLineNumber.foreground": "#8C959F",
        "editorIndentGuide.background": "#D8DEE4",
      },
    },
  },
  "solarized-dark": {
    label: "Solarized Dark",
    mode: "dark",
    monacoTheme: "solarized-dark",
    cssVars: {
      "--background": "193 100% 8%",
      "--foreground": "186 13% 55%",
      "--card": "193 100% 10%",
      "--card-border": "193 80% 14%",
      "--sidebar": "193 100% 11%",
      "--sidebar-border": "193 80% 15%",
      "--border": "193 80% 15%",
      "--primary": "205 69% 49%",
      "--primary-foreground": "0 0% 98%",
      "--ring": "205 69% 49%",
      "--sidebar-primary": "205 69% 49%",
      "--sidebar-ring": "205 69% 49%",
      "--accent": "193 80% 15%",
      "--accent-foreground": "180 62% 58%",
      "--muted": "193 80% 14%",
      "--muted-foreground": "186 12% 45%",
    },
    customTheme: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", foreground: "839496", background: "002B36" },
        { token: "comment", foreground: "586E75", fontStyle: "italic" },
        { token: "keyword", foreground: "859900" },
        { token: "string", foreground: "2AA198" },
        { token: "number", foreground: "D33682" },
        { token: "type", foreground: "B58900" },
        { token: "function", foreground: "268BD2" },
        { token: "variable", foreground: "B58900" },
        { token: "constant", foreground: "CB4B16" },
        { token: "tag", foreground: "268BD2" },
        { token: "attribute.name", foreground: "93A1A1" },
        { token: "attribute.value", foreground: "2AA198" },
        { token: "delimiter", foreground: "839496" },
        { token: "operator", foreground: "859900" },
      ],
      colors: {
        "editor.background": "#002B36",
        "editor.foreground": "#839496",
        "editorCursor.foreground": "#D30102",
        "editor.selectionBackground": "#073642",
        "editor.lineHighlightBackground": "#073642",
        "editorLineNumber.foreground": "#586E75",
        "editorIndentGuide.background": "#073642",
      },
    },
  },
  "solarized-light": {
    label: "Solarized Light",
    mode: "light",
    monacoTheme: "solarized-light",
    cssVars: {
      "--background": "44 100% 95%",
      "--foreground": "192 81% 14%",
      "--card": "44 87% 92%",
      "--card-border": "44 50% 85%",
      "--sidebar": "44 65% 90%",
      "--sidebar-border": "44 50% 83%",
      "--border": "44 50% 83%",
      "--primary": "205 69% 49%",
      "--primary-foreground": "0 0% 98%",
      "--ring": "205 69% 49%",
      "--sidebar-primary": "205 69% 49%",
      "--sidebar-ring": "205 69% 49%",
      "--accent": "44 50% 84%",
      "--accent-foreground": "193 100% 18%",
      "--muted": "44 50% 87%",
      "--muted-foreground": "192 30% 40%",
    },
    customTheme: {
      base: "vs",
      inherit: true,
      rules: [
        { token: "", foreground: "657B83", background: "FDF6E3" },
        { token: "comment", foreground: "93A1A1", fontStyle: "italic" },
        { token: "keyword", foreground: "859900" },
        { token: "string", foreground: "2AA198" },
        { token: "number", foreground: "D33682" },
        { token: "type", foreground: "B58900" },
        { token: "function", foreground: "268BD2" },
        { token: "variable", foreground: "B58900" },
        { token: "constant", foreground: "CB4B16" },
        { token: "tag", foreground: "268BD2" },
        { token: "attribute.name", foreground: "93A1A1" },
        { token: "attribute.value", foreground: "2AA198" },
        { token: "delimiter", foreground: "657B83" },
        { token: "operator", foreground: "859900" },
      ],
      colors: {
        "editor.background": "#FDF6E3",
        "editor.foreground": "#657B83",
        "editorCursor.foreground": "#D30102",
        "editor.selectionBackground": "#EEE8D5",
        "editor.lineHighlightBackground": "#EEE8D5",
        "editorLineNumber.foreground": "#93A1A1",
        "editorIndentGuide.background": "#EEE8D5",
      },
    },
  },
  abyss: {
    label: "Abyss",
    mode: "dark",
    monacoTheme: "abyss",
    cssVars: {
      "--background": "214 100% 4%",
      "--foreground": "225 44% 72%",
      "--card": "214 100% 6%",
      "--card-border": "220 60% 12%",
      "--sidebar": "214 100% 7%",
      "--sidebar-border": "220 60% 13%",
      "--border": "220 60% 13%",
      "--primary": "225 60% 65%",
      "--primary-foreground": "0 0% 98%",
      "--ring": "225 60% 65%",
      "--sidebar-primary": "225 60% 65%",
      "--sidebar-ring": "225 60% 65%",
      "--accent": "220 60% 14%",
      "--accent-foreground": "225 70% 80%",
      "--muted": "220 60% 12%",
      "--muted-foreground": "225 30% 55%",
    },
    customTheme: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", foreground: "6688CC", background: "000C18" },
        { token: "comment", foreground: "384887", fontStyle: "italic" },
        { token: "keyword", foreground: "225588" },
        { token: "string", foreground: "22AA44" },
        { token: "number", foreground: "F280D0" },
        { token: "type", foreground: "DDBB88" },
        { token: "function", foreground: "DDBB88" },
        { token: "variable", foreground: "6688CC" },
        { token: "constant", foreground: "F280D0" },
        { token: "tag", foreground: "225588" },
        { token: "attribute.name", foreground: "DDBB88" },
        { token: "attribute.value", foreground: "22AA44" },
        { token: "delimiter", foreground: "6688CC" },
        { token: "operator", foreground: "225588" },
      ],
      colors: {
        "editor.background": "#000C18",
        "editor.foreground": "#6688CC",
        "editorCursor.foreground": "#DDBB88",
        "editor.selectionBackground": "#770811",
        "editor.lineHighlightBackground": "#082050",
        "editorLineNumber.foreground": "#384887",
        "editorIndentGuide.background": "#1B2738",
      },
    },
  },
  "tomorrow-night-blue": {
    label: "Tomorrow Night Blue",
    mode: "dark",
    monacoTheme: "tomorrow-night-blue",
    cssVars: {
      "--background": "214 100% 13%",
      "--foreground": "0 0% 95%",
      "--card": "214 100% 15%",
      "--card-border": "214 80% 20%",
      "--sidebar": "214 100% 16%",
      "--sidebar-border": "214 80% 21%",
      "--border": "214 80% 21%",
      "--primary": "214 100% 74%",
      "--primary-foreground": "214 100% 10%",
      "--ring": "214 100% 74%",
      "--sidebar-primary": "214 100% 74%",
      "--sidebar-ring": "214 100% 74%",
      "--accent": "214 80% 22%",
      "--accent-foreground": "214 100% 85%",
      "--muted": "214 80% 20%",
      "--muted-foreground": "214 40% 65%",
    },
    customTheme: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", foreground: "FFFFFF", background: "002451" },
        { token: "comment", foreground: "7285B7", fontStyle: "italic" },
        { token: "keyword", foreground: "EBBBFF" },
        { token: "string", foreground: "D1F1A9" },
        { token: "number", foreground: "FFC58F" },
        { token: "type", foreground: "FFEEAD" },
        { token: "function", foreground: "BBDAFF" },
        { token: "variable", foreground: "FFEEAD" },
        { token: "constant", foreground: "FFC58F" },
        { token: "tag", foreground: "FF9DA4" },
        { token: "attribute.name", foreground: "FFEEAD" },
        { token: "attribute.value", foreground: "D1F1A9" },
        { token: "delimiter", foreground: "FFFFFF" },
        { token: "operator", foreground: "99FFFF" },
      ],
      colors: {
        "editor.background": "#002451",
        "editor.foreground": "#FFFFFF",
        "editorCursor.foreground": "#FFFFFF",
        "editor.selectionBackground": "#003F8E",
        "editor.lineHighlightBackground": "#00346E",
        "editorLineNumber.foreground": "#7285B7",
        "editorIndentGuide.background": "#1F4662",
      },
    },
  },
  "quiet-light": {
    label: "Quiet Light",
    mode: "light",
    monacoTheme: "quiet-light",
    cssVars: {
      "--primary": "2 52% 44%",
      "--primary-foreground": "0 0% 98%",
      "--ring": "2 52% 44%",
      "--sidebar-primary": "2 52% 44%",
      "--sidebar-ring": "2 52% 44%",
      "--accent": "2 30% 90%",
      "--accent-foreground": "2 50% 25%",
    },
    customTheme: {
      base: "vs",
      inherit: true,
      rules: [
        { token: "", foreground: "333333", background: "F5F5F5" },
        { token: "comment", foreground: "AAAAAA", fontStyle: "italic" },
        { token: "keyword", foreground: "4B69C6" },
        { token: "string", foreground: "448C27" },
        { token: "number", foreground: "AB6526" },
        { token: "type", foreground: "7A3E9D" },
        { token: "function", foreground: "AA3731" },
        { token: "variable", foreground: "7A3E9D" },
        { token: "constant", foreground: "AB6526" },
        { token: "tag", foreground: "4B69C6" },
        { token: "attribute.name", foreground: "AA3731" },
        { token: "attribute.value", foreground: "448C27" },
        { token: "delimiter", foreground: "333333" },
        { token: "operator", foreground: "777777" },
      ],
      colors: {
        "editor.background": "#F5F5F5",
        "editor.foreground": "#333333",
        "editorCursor.foreground": "#54494B",
        "editor.selectionBackground": "#C9D0D9",
        "editor.lineHighlightBackground": "#E4E6E7",
        "editorLineNumber.foreground": "#AAAAAA",
        "editorIndentGuide.background": "#E0E0E0",
      },
    },
  },
};

export function getThemeConfig(id: ThemeId): ThemeConfig {
  return THEMES[id] || THEMES["vs-dark"];
}

export function isValidThemeId(id: string): id is ThemeId {
  return id in THEMES;
}
